#!/usr/bin/env python3
import argparse
import json
from collections import Counter, defaultdict
from typing import Dict, List, Any


def load_analysis(path: str) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def group_by_effect_type(tests: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
    groups: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for t in tests:
        et = t.get("effect_type", "")
        groups[et].append(t)
    return groups


def filter_tests(tests: List[Dict[str, Any]], effect_type: str = None, id_contains: str = None) -> List[Dict[str, Any]]:
    out = []
    for t in tests:
        if effect_type and t.get("effect_type") != effect_type:
            continue
        if id_contains and id_contains not in t.get("id", ""):
            continue
        out.append(t)
    return out


def payload_to_bytes(payload_hex: str) -> bytes:
    payload_hex = payload_hex.replace(":", "").replace(" ", "")
    try:
        return bytes.fromhex(payload_hex)
    except ValueError:
        return b""


def diff_payloads(payloads: List[str]) -> Dict[int, Dict[str, Any]]:
    """Return a map of byte index -> {values, stable}.

    values: Counter of observed byte values at this position.
    stable: True if only one value observed.
    """
    if not payloads:
        return {}

    byte_rows = [payload_to_bytes(p) for p in payloads]
    max_len = max(len(b) for b in byte_rows)

    result: Dict[int, Dict[str, Any]] = {}
    for i in range(max_len):
        vals = []
        for row in byte_rows:
            if i < len(row):
                vals.append(row[i])
        counter = Counter(vals)
        result[i] = {"values": dict(counter), "stable": len(counter) == 1}
    return result


def collect_representative_payloads(test_entry: Dict[str, Any]) -> List[str]:
    top_payloads = test_entry.get("usb_summary", {}).get("top_payloads", [])
    payloads = [p.get("capdata") for p in top_payloads if isinstance(p, dict) and p.get("capdata")]
    # Fallback to sample frames if no aggregated payloads exist
    if not payloads:
        for frame in test_entry.get("usb_summary", {}).get("sample_frames", []):
            cap = frame.get("capdata")
            if cap:
                payloads.append(cap)
    return payloads


def compare_group(tests: List[Dict[str, Any]], label: str) -> None:
    print(f"=== Group: {label} (n={len(tests)}) ===")
    if not tests:
        print("(no tests)")
        return

    # Print IDs and a short summary of their top payloads
    for t in tests:
        test_id = t.get("id")
        effect_type = t.get("effect_type")
        summary = t.get("usb_summary", {}) or {}
        total = summary.get("total_lines", summary.get("total_frames", 0))
        unique = summary.get("unique_payloads", 0)
        print(f"- {test_id} [{effect_type}] frames={total} unique_payloads={unique}")

    # Flatten representative payloads for the group
    all_payloads: List[str] = []
    for t in tests:
        all_payloads.extend(collect_representative_payloads(t))

    diffs = diff_payloads(all_payloads)
    changing_positions = [i for i, info in diffs.items() if not info["stable"]]
    print(f"Byte positions that vary across this group: {changing_positions}")

    # Show the distribution at each varying position
    for i in changing_positions:
        info = diffs[i]
        vals = ", ".join(f"0x{b:02x}x{cnt}" for b, cnt in sorted(info["values"].items()))
        print(f"  index {i}: {vals}")

    print()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Compare USB payload patterns across tests using analysis.json",
    )
    parser.add_argument(
        "--analysis",
        default="captures/analysis.json",
        help="Path to analysis.json generated by analyze_usb_pcaps.py",
    )
    parser.add_argument(
        "--effect-type",
        help="Filter tests by effect type (e.g., constant, sine, ramp, spring)",
    )
    parser.add_argument(
        "--id-contains",
        help="Filter tests whose ID contains this substring (e.g., 'constant_level_', 'ramp_')",
    )

    args = parser.parse_args()
    analysis = load_analysis(args.analysis)
    tests = analysis.get("tests", [])

    filtered = filter_tests(tests, effect_type=args.effect_type, id_contains=args.id_contains)

    # Further group by effect type to make patterns clearer
    groups = group_by_effect_type(filtered)
    for effect_type, group in sorted(groups.items()):
        label = effect_type
        if args.id_contains:
            label += f" (id contains '{args.id_contains}')"
        compare_group(group, label)


if __name__ == "__main__":
    main()

